//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementKonovalov.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatProject
    {
        public int IdChatProject { get; set; }
        public int IdProject { get; set; }
        public int IdStaff { get; set; }
        public string Message { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
