//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementKonovalov.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckSheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CheckSheet()
        {
            this.Task = new HashSet<Task>();
        }
    
        public int IdCheckSheet { get; set; }
        public string NameCheckSheet { get; set; }
        public Nullable<int> IdStatusTask { get; set; }
    
        public virtual StatusTask StatusTask { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Task { get; set; }
    }
}
