//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementKonovalov.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passport
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Passport()
        {
            this.Staff = new HashSet<Staff>();
        }
    
        public int IdPassport { get; set; }
        public int SeriesPassport { get; set; }
        public int NumberPassport { get; set; }
        public string DepartmentCodePassport { get; set; }
        public string RegistrationAddressPassport { get; set; }
        public int IdIssuedByWhom { get; set; }
        public int IdStatusDelete { get; set; }
    
        public virtual IssuedByWhom IssuedByWhom { get; set; }
        public virtual StatusDelete StatusDelete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff> Staff { get; set; }
    }
}
