//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementKonovalov.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int IdReport { get; set; }
        public int CountOfCompletedLowTasks { get; set; }
        public int CountOfCompletedMediumTasks { get; set; }
        public int CountOfCompletedHeightTasks { get; set; }
        public System.DateTime DatePeriodStart { get; set; }
        public System.DateTime DatePriodEnd { get; set; }
        public int CountOfCompletedDeadlines { get; set; }
        public int CountOfUncomplatedDeadlines { get; set; }
        public System.DateTime DateReport { get; set; }
        public int IdStaff { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
