//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementKonovalov.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.Report = new HashSet<Report>();
            this.Task = new HashSet<Task>();
        }
    
        public int IdStaff { get; set; }
        public string LastNameStaff { get; set; }
        public string FirstNameStaff { get; set; }
        public string MiddleNameStaff { get; set; }
        public string NumberPhoneStaff { get; set; }
        public System.DateTime DateOfBirthStaff { get; set; }
        public int IdGender { get; set; }
        public string AdressStaff { get; set; }
        public int IdJobTitle { get; set; }
        public int IdUser { get; set; }
        public byte[] PhotoStaff { get; set; }
        public int IdPassport { get; set; }
        public int IdStatusDelete { get; set; }
        public string Email { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual JobTitle JobTitle { get; set; }
        public virtual Passport Passport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Report> Report { get; set; }
        public virtual StatusDelete StatusDelete { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Task { get; set; }
    }
}
